spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/user_service_db
    username: root
    password: fred
    driver-class-name: org.mariadb.jdbc.Driver

  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration
    schemas: user_service_db
  server:
    port: 8091
