spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/user_service_db
    username: root
    password: fred
    driver-class-name: org.mariadb.jdbc.Driver
  mybatis:
    # Nơi chứa các XML mapper nếu có
    mapper-locations: classpath:mapper/*.xml
    # Nơi chứa các class model (alias name)
    type-aliases-package: com.example.model
    configuration:
      map-underscore-to-camel-case: true
      log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
  server:
    port: 8091