spring:
  45config:
      import: optional:configserver:http://localhost:8887
  application:
    name: discovery-service

eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}/${server.port}/eureka/
server:
  port: 8760
